apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: pers.edwin@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector:
        dnsZones:
        - pm8s.io
      dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-key-secret
            key: api-key
        cnameStrategy: Follow
